services:
  db:
    image: mysql:8
    container_name: my-project-db
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=my_database
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: my-project-backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=example
      - DB_NAME=my_database
    volumes:
      - ./backend:/app
    command: ["npm", "run", "dev"]

  frontend:
    build: ./frontend
    container_name: my-project-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

volumes:
  db-data:
